### ISSUE TITLE
Accessibility: Each <nav> on a page must have a unique label

### ISSUE THREAD

**Issue by lesa-mcpeak** [washingtonstateuniversity/wsu-web-design-system#12]
https://github.com/washingtonstateuniversity/wsu-web-design-system/blob/5fd61daa89ce0b9e507f3d8ef57902a8e9fcbf7a/components/src/global-header/global-header.html#L23

https://www.w3.org/TR/wai-aria-practices-1.1/#aria_landmark
https://www.w3.org/TR/wai-aria-practices-1.1/#aria_lh_navigation
https://www.w3.org/WAI/tutorials/page-structure/regions/#navigation
https://www.w3.org/TR/2017/NOTE-wai-aria-practices-1.1-20171214/examples/landmarks/navigation.html

**Comment by nicdford** [comment]
Note to self: Going to close #13 and include the changes in this issue.

**Comment by nicdford** [comment]
Fixed with a58732f0a0c481c14dd2e6b6967c00f89e03a0b5
