### ISSUE TITLE
Accessibility: Each <nav> on a page must have a unique label

### ISSUE THREAD

**Issue by lesa-mcpeak** [washingtonstateuniversity/wsu-web-design-system#13]
https://github.com/washingtonstateuniversity/wsu-web-design-system/blob/5fd61daa89ce0b9e507f3d8ef57902a8e9fcbf7a/components/src/global-footer/global-footer.html#L22

Same as Issue #12 https://github.com/washingtonstateuniversity/wsu-web-design-system/issues/12

**Comment by nicdford** [comment]
Closing in favor of #12 since i'll fix them at the same time.
