### ISSUE TITLE
accessibility of svg

### ISSUE THREAD

**Issue by lesa-mcpeak** [washingtonstateuniversity/wsu-web-design-system#6]
https://github.com/washingtonstateuniversity/wsu-web-design-system/blob/cd2f8fa0a7620271cd793bcb26359d19dabfd807/components/src/global-header/global-header.html#L19
This img should have role="img" and must have alt=""
https://www.deque.com/blog/creating-accessible-svgs/

**Comment by nicdford** [comment]
Closing in favor of using #7 to consolidate fixes
