### ISSUE TITLE
Button text colors

### ISSUE THREAD

**Issue by charlesjdillon** [washingtonstateuniversity/wsu-web-design-system#64]
Chrome Version 79.0.3945.130 (Official Build) (64-bit)
Mac Mojavi 10.14.6
https://stage.web.wsu.edu/web-design-system/demo-buttons/#

Buttons do not have enough contrast between text and background. 

<img width="1456" alt="Screen Shot 2020-02-11 at 10 24 42 AM" src="https://user-images.githubusercontent.com/4007184/74266588-5fe93080-4cb9-11ea-8ccd-a5cfc9560eb4.png">

**Comment by nicdford** [comment]
Fixed with #fe8936a72c265c769a378cb1aa8133257a26bbd5 :)
