### ISSUE TITLE
Accessibility of SVG

### ISSUE THREAD

**Issue by lesa-mcpeak** [washingtonstateuniversity/wsu-web-design-system#7]
https://github.com/washingtonstateuniversity/wsu-web-design-system/blob/cd2f8fa0a7620271cd793bcb26359d19dabfd807/components/src/global-header/global-header.html#L44

This img should have role="img" and must have alt="search"
https://www.deque.com/blog/creating-accessible-svgs/

**Comment by nicdford** [comment]
Hey @lesa-mcpeak thanks for this! In your opinion is SVG pattern 5 the best option for us? We're using inline svg's in the final product, so the first 4 examples are a no-go. Thanks for the feedback!

**Comment by lesa-mcpeak** [comment]
@nicdford I would go with pattern 11. When a desc is needed on an svg the pattern of code is already established.

**Comment by nicdford** [comment]
Note to self: fix #6 as part of this issue as well

**Comment by nicdford** [comment]
With the adoption of the WSU Icon Font Family (#23) This should remove the need for these changes except in the case of the **coug head** which **will always be an inline svg element**.

**Comment by nicdford** [comment]
Fixed with 095b1f241149e490feda7c9b92551bfc54a23ed1
