### ISSUE TITLE
Cleanup Stories

### ISSUE THREAD

**Issue by nicdford** [washingtonstateuniversity/wsu-web-design-system#97]
- [x] Use tabs, not spaces
- [x] components-content-card doesn't follow the previewGroupID/optionsGroupID paradigm for knobs
![image](https://user-images.githubusercontent.com/7292444/101830606-9e25cb00-3ae9-11eb-9aab-b8125e9f955b.png)
- [x] Default column story missing layout/wrapper knobs
- [x] Column bleed story layout/wrapper knobs not working
- [x] All heading stories are broken
- [x] Hero banner missing layout/wrapper knobs
- [x] Default icon story broken
- [x] Loading icon is broken
- [x] Modal is broken
- [x] Check that knobs work :)

**Comment by ErikSolveson** [comment]
@nicdford - I finished this 4 years ago
